services:
  - docker:dind

stages:
  - build
  - test

build:
  image: docker:latest
  stage: build
  tags:
    - tokend
  script:
    - echo "bulding"
    - sleep 5
    - echo "done"

unit_tests:
  image: golang:latest
  stage: test
  tags:
    - tokend
  # total:                                                  (statements)    44.4%
  coverage: '/total:.+[0-9\.]+%$/'
  script:
    - go test -v -covermode=count -coverprofile=./coverage.out ./...
    - go tool cover -func=./coverage.out

#integration_tests:
#  image: docker:latest
#  stage: test
#  tags:
#    - tokend
#  script:
#    - echo "running unit tests"
#    - sleep 40
#    - echo "done"