services:
  - docker:dind

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - coverage/

stages:
  - build
  - test
  - report

build:
  image: docker:latest
  stage: build
  tags:
    - tokend
  script:
    - echo "bulding"
    - sleep 5
    - echo "done"

unit_tests:
  image: golang:latest
  stage: test
  tags:
    - tokend
  script:
    - go test -v -covermode=count -coverprofile=./coverage/report ./...

unit_coverage:
  image: golang:latest
  stage: report
  # total:                                                  (statements)    44.4%
  coverage: '/total:.+[0-9\.]+%$/'
  dependencies:
    - unit_tests
  script:
    go tool cover -func=./coverage/report

#integration_tests:
#  image: docker:latest
#  stage: test
#  tags:
#    - tokend
#  script:
#    - echo "running unit tests"
#    - sleep 40
#    - echo "done"